Fix ConstraintViolationError exception string when exprs are int
As titled. If `expr1` `expr2` are int, don't need to do `.xreplace`.

See example error:

```
UserError: L['args'][0][0].size()[1] = 35 is not equal to L['args'][0][2].size()[1] = 23
```

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

ghstack-source-id: 8830499f83f46a9ea03dc0ae5f3dbd2e47cd5dff
Pull Request resolved: https://github.com/pytorch/pytorch/pull/129271